version: '3.1'

networks: 
    production-network:
        driver: bridge

services:
    mysql56:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql56
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: databasetcp
        networks: 
            - production-network
    app:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: andersonsilva/app
        container_name: app
        ports:
            - "8080:8080"
        networks: 
            - production-network
        links: 
            - "mysql56:mysql"
        depends_on:
            - "mysql56"